//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinema_Dükkanı
{
    using System;
    using System.Collections.Generic;
    
    public partial class filmler
    {
        public filmler()
        {
            this.satıslar = new HashSet<satıslar>();
            this.satıslar1 = new HashSet<satıslar>();
            this.oyunculars = new HashSet<oyuncular>();
            this.türler = new HashSet<türler>();
        }
    
        public int filmid { get; set; }
        public string filmad { get; set; }
        public string konu { get; set; }
        public Nullable<int> yönetmenid { get; set; }
        public Nullable<int> sure { get; set; }
        public Nullable<System.DateTime> vizyontarihi { get; set; }
        public Nullable<double> fiyat { get; set; }
        public Nullable<int> stok { get; set; }
    
        public virtual yöntemenler yöntemenler { get; set; }
        public virtual ICollection<satıslar> satıslar { get; set; }
        public virtual ICollection<satıslar> satıslar1 { get; set; }
        public virtual ICollection<oyuncular> oyunculars { get; set; }
        public virtual ICollection<türler> türler { get; set; }
    }
}
