//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinema_Dükkanı
{
    using System;
    using System.Collections.Generic;
    
    public partial class müsteriler
    {
        public müsteriler()
        {
            this.satıslar = new HashSet<satıslar>();
        }
    
        public int müsid { get; set; }
        public string adsoyad { get; set; }
        public string tcno { get; set; }
        public string adres { get; set; }
        public string telefon { get; set; }
        public Nullable<System.DateTime> kayıttarihi { get; set; }
    
        public virtual ICollection<satıslar> satıslar { get; set; }
    }
}
