//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinema_Dükkanı
{
    using System;
    using System.Collections.Generic;
    
    public partial class oyuncular
    {
        public oyuncular()
        {
            this.filmlers = new HashSet<filmler>();
        }
    
        public int oyuncuid { get; set; }
        public string adısoyadı { get; set; }
        public Nullable<System.DateTime> dogumtarihi { get; set; }
        public string memleket { get; set; }
    
        public virtual ICollection<filmler> filmlers { get; set; }
    }
}
