//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinema_Dükkanı
{
    using System;
    using System.Collections.Generic;
    
    public partial class satıslar
    {
        public int satısid { get; set; }
        public Nullable<int> müsid { get; set; }
        public Nullable<int> filmid { get; set; }
        public Nullable<System.DateTime> satıstarih { get; set; }
        public Nullable<int> adet { get; set; }
        public Nullable<double> fiyat { get; set; }
        public Nullable<double> tutar { get; set; }
    
        public virtual filmler filmler { get; set; }
        public virtual filmler filmler1 { get; set; }
        public virtual müsteriler müsteriler { get; set; }
    }
}
