//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinema_Dükkanı
{
    using System;
    using System.Collections.Generic;
    
    public partial class türler
    {
        public türler()
        {
            this.filmlers = new HashSet<filmler>();
        }
    
        public int türid { get; set; }
        public string türad { get; set; }
    
        public virtual ICollection<filmler> filmlers { get; set; }
    }
}
